# Generated by Django 3.2.5 on 2021-07-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20191202_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due To'),
        ),
    ]
