# Generated by Django 3.2.5 on 2021-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='send_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='send_to',
            field=models.BooleanField(default=False),
        ),
    ]
