# Generated by Django 3.2.5 on 2021-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_auto_20210703_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='read_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='isCompleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='send_from',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='send_to',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
